- hosts: localhost
  become: yes
  vars:
    jenkins_hostname: localhost
    java_packages:
      - openjdk-8-jdk
    docker_users:
    - jenkins
  roles:
    - role: geerlingguy.jenkins
    - role: geerlingguy.docker